### ISSUE TITLE
点击"Send"后没反应

### ISSUE THREAD

**Issue by mengcius** [Hujiazeng/Vach#12]
点击"Send"后什么反应也没有，一直播放的是默认视频，终端没有反应

**Comment by Dzy0815** [comment]
是的，我也遇到了这个问题，后端加了打印信息，发现能收到信息并显示内容，但是视频没有变化

**Comment by lmpeng12** [comment]
我这边也是实现了有关的连接，并且发送了数据，但是发觉没有实现改变唇形的处理步骤，debug发觉是有生成音频的，但是好像没有去调用唇音同步的步骤，cu117，torch2.0.1的版本

**Comment by ccpjcmjs** [comment]
我改了下源码有反应了
![image](https://github.com/Hujiazeng/Vach/assets/56874902/1af86723-2711-4664-a065-7875be94a0fc)

**Comment by lmpeng12** [comment]
> 我改了下源码有反应了 ![image](https://private-user-images.githubusercontent.com/56874902/336804369-1af86723-2711-4664-a065-7875be94a0fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODYzNTksIm5iZiI6MTcxNzU4NjA1OSwicGF0aCI6Ii81Njg3NDkwMi8zMzY4MDQzNjktMWFmODY3MjMtMjcxMS00NjY0LWEwNjUtNzg3NWJlOTRhMGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTE3ZmY1OGQ2OWFhNmRmMjczYjViNTFkYjZlNzlmMjQ4YzRhMTM5OWU5NmUxNzI1Njg5NmNiMjM4MTQzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._g_MyQuo8QOhTSK98tJYIZfSMxUjN4w5SkJvbiYlk2Y)

可以了，感谢大佬

**Comment by fingerx** [comment]
@lmpeng12  有测试win 系统吗？

**Comment by ydcydc26** [comment]
windows声音很卡
