### ISSUE TITLE
全是报错 readme该更新了吧

### ISSUE THREAD

**Issue by haomole** [Hujiazeng/Vach#20]
C:/ProgramData/anaconda3/envs/Vach/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
C:\Users\DELL\Desktop\Vach-dev\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(33): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:\Users\DELL\Desktop\Vach-dev\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(34): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:\Users\DELL\Desktop\Vach-dev\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(35): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:\Users\DELL\Desktop\Vach-dev\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(36): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:\Users\DELL\Desktop\Vach-dev\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(37): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:/ProgramData/anaconda3/envs/Vach/lib/site-packages/torch/include\c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: invalid combination of type specifiers

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: expected an identifier

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name

3 errors detected in the compilation of "C:/Users/DELL/Desktop/Vach-dev/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 2

**Comment by 807502278** [comment]
need cuda11.3
