### ISSUE TITLE
在autodl 云服务器上面搭建起了，但是视频不出来呢

### ISSUE THREAD

**Issue by fengxingshenzhou** [Hujiazeng/Vach#21]
![1722305829514](https://github.com/user-attachments/assets/df593381-04e9-46f8-843c-ea28f42abdf5)
![1722305876621](https://github.com/user-attachments/assets/4e07bba4-fd3f-467e-a666-a6b0fef04668)
有没有大神遇到过这种情况

**Comment by xiaomaofei** [comment]
我也遇到和你一样的情况，我的链接网页都打不开

**Comment by fengxingshenzhou** [comment]
我换项目了，这个浪费了两天时间，不知道是不是端口的问题，还是用metahuman-stream吧

**Comment by 1145141919** [comment]
请教一下！autodl上的云服务器里要怎么打开浏览器呢？

**Comment by 1145141919** [comment]
> 我也遇到和你一样的情况，我的链接网页都打不开

请教一下！autodl上的云服务器里要怎么打开浏览器呢？

**Comment by fengxingshenzhou** [comment]
> > 我也遇到和你一样的情况，我的链接网页都打不开
> 
> 请教一下！autodl上的云服务器里要怎么打开浏览器呢？

用隧道

**Comment by no996no007** [comment]
我也是卡在了这一步，老铁最后是怎么解决的呀？

**Comment by Hujiazeng** [comment]
需要开放端口 tcp:8000,8010,1985; udp:8000
