### ISSUE TITLE
大佬 执行 pip install ./freqencoder  报错ERROR: Invalid requirement: './freqencoder' 没有看到 项目下有freqencoder 这个目录 

### ISSUE THREAD

**Issue by anstonjie** [Hujiazeng/Vach#4]
pip install ./freqencoder
pip install ./shencoder
pip install ./gridencoder
pip install ./raymarching

pip install ./freqencoder  报错ERROR: Invalid requirement: './freqencoder' 没有看到 项目下有freqencoder 这个目录 
这些目录都是怎么产生的 谢谢

**Comment by anstonjie** [comment]
我是在Anaconda Prompt里执行的

**Comment by Hujiazeng** [comment]
进入内嵌的数字人项目里执行
