### ISSUE TITLE
websocket调用失败

### ISSUE THREAD

**Issue by gemini0524** [Hujiazeng/Vach#7]
![WX20240524-220502@2x](https://github.com/Hujiazeng/Vach/assets/3241234/612ae7b6-3a3f-48a9-9208-f87dd75d87fa)
出了这么一个错

**Comment by Hujiazeng** [comment]
降低flask版本

**Comment by louyuanyuan053709** [comment]
可以参考 https://zhuanlan.zhihu.com/p/677917890 中的方法二
![飞书20240527-153039](https://github.com/Hujiazeng/Vach/assets/169432626/0eea0524-70fb-4bf6-a7a0-0cfd0a1ee6c5)
